### ISSUE TITLE
Integrate Poetry package to manage dependencies and add instructions in Readme.md

### ISSUE THREAD

**Issue by AndrewPBerg** [AndrewPBerg/posture-productivity#13]
To share a Poetry project that depends on a public repository, you can specify the dependency in your `pyproject.toml` file under the `[tool.poetry.dependencies]` section. Poetry supports adding dependencies from various sources, including public repositories.

Here’s how you can specify different types of dependencies:

### 1. Dependencies from PyPI

These are the typical dependencies you add from the Python Package Index (PyPI):

```toml
[tool.poetry.dependencies]
python = "^3.8"
mediapipe = "^0.9.3.0"
opencv-python-headless = "^4.5.5.64"
PySimpleGUI = "^4.58.0"
```

### 2. Dependencies from a Public Git Repository

If you need to add a dependency directly from a public Git repository, you can do so by specifying the Git URL. You can also specify a branch, tag, or commit hash.

```toml
[tool.poetry.dependencies]
some-package = { git = "https://github.com/user/repo.git", branch = "main" }
```

Example with a specific tag:

```toml
[tool.poetry.dependencies]
some-package = { git = "https://github.com/user/repo.git", tag = "v1.0.0" }
```

Example with a specific commit:

```toml
[tool.poetry.dependencies]
some-package = { git = "https://github.com/user/repo.git", rev = "commit-hash" }
```

### 3. Dependencies from a Specific URL

You can also add dependencies from a specific URL if the package is hosted somewhere other than PyPI:

```toml
[tool.poetry.dependencies]
some-package = { url = "https://example.com/some-package-1.0.0.tar.gz" }
```

### 4. Custom PyPI Index

If your package is hosted on a custom PyPI index, you can specify this index in your `pyproject.toml`:

```toml
[[tool.poetry.source]]
name = "custom"
url = "https://custom.pypi.repo/simple/"
default = false

[tool.poetry.dependencies]
some-package = { version = "^1.0.0", source = "custom" }
```

### Full Example

Here’s an example `pyproject.toml` that includes various types of dependencies:

```toml
[tool.poetry]
name = "your_project_name"
version = "0.1.0"
description = "Description of your project"
authors = ["Your Name <youremail@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
mediapipe = "^0.9.3.0"
opencv-python-headless = "^4.5.5.64"
PySimpleGUI = "^4.58.0"
some-package = { git = "https://github.com/user/repo.git", branch = "main" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Sharing the Project

When sharing your project, ensure you include the `pyproject.toml` and `poetry.lock` files in your repository. These files define the project’s dependencies and ensure that anyone who clones your repository can recreate the exact environment.

### Installation

To install the dependencies for your project, a user would simply clone the repository and run:

```sh
poetry install
```

This command reads the `pyproject.toml` and `poetry.lock` files, creates a virtual environment, and installs all the dependencies specified.

### Example Repository Structure

Your project repository might look like this:

```
project_directory/
│
├── pose_utils.py          # Contains the is_standing function
├── main_script.py         # Main script with the GUI and pose detection
├── pyproject.toml         # Poetry configuration file
├── poetry.lock            # Poetry lock file for dependency versions
```

By following these steps, you can easily share your Poetry-managed project and ensure that others can install and use it with all the correct dependencies.
